/** Figurenmuster, Zeichen siehe PALETTE in pixelart.ts. `P`/`Q` sind Spielerfarbe und Schatten. */
export type PlayerFrame = 'down_a' | 'down_b' | 'up_a' | 'up_b' | 'side_a' | 'side_b' | 'lying';

/** Spielerfigur 12x12. `side` blickt nach rechts (links per flipX). */
export const PLAYER_SPRITES: Record<PlayerFrame, readonly string[]> = {
  down_a: [
    '............',
    '...kkkkkk...',
    '..kssssssk..',
    '..kskssksk..',
    '..kssssssk..',
    '...kkkkkk...',
    '.kPPPPPPPPk.',
    '.ksPPPPPPsk.',
    '.kkPQQQQPkk.',
    '..kBBkkBBk..',
    '..kkkkkkkk..',
    '............',
  ],
  down_b: [
    '............',
    '...kkkkkk...',
    '..kssssssk..',
    '..kskssksk..',
    '..kssssssk..',
    '...kkkkkk...',
    '.kPPPPPPPPk.',
    '.ksPPPPPPsk.',
    '.kkPQQQQPkk.',
    '.kBBk..kBBk.',
    '.kkkk..kkkk.',
    '............',
  ],
  up_a: [
    '............',
    '...kkkkkk...',
    '..kNNNNNNk..',
    '..kNNNNNNk..',
    '..kNNNNNNk..',
    '...kkkkkk...',
    '.kPPPPPPPPk.',
    '.ksPQQQQPsk.',
    '.kkPQQQQPkk.',
    '..kBBkkBBk..',
    '..kkkkkkkk..',
    '............',
  ],
  up_b: [
    '............',
    '...kkkkkk...',
    '..kNNNNNNk..',
    '..kNNNNNNk..',
    '..kNNNNNNk..',
    '...kkkkkk...',
    '.kPPPPPPPPk.',
    '.ksPQQQQPsk.',
    '.kkPQQQQPkk.',
    '.kBBk..kBBk.',
    '.kkkk..kkkk.',
    '............',
  ],
  side_a: [
    '............',
    '...kkkkkk...',
    '..kNNNNsk...',
    '..kNNsksk...',
    '..kNNsssskk.',
    '...kkkkkk...',
    '..kPPPPPPk..',
    '..kPPPPPsk..',
    '..kPQQQQPk..',
    '...kBBBBk...',
    '...kkkkkk...',
    '............',
  ],
  side_b: [
    '............',
    '...kkkkkk...',
    '..kNNNNsk...',
    '..kNNsksk...',
    '..kNNsssskk.',
    '...kkkkkk...',
    '..kPPPPPPk..',
    '..kPPPPPsk..',
    '..kPQQQQPk..',
    '..kBBkkBBk..',
    '.kkkkk.kkkk.',
    '............',
  ],
  lying: [
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '.kkkkkkkkkk.',
    'kNNsskPPPPPk',
    'ksksskPQQBBk',
    'ksssskPPPBBk',
    '.kkkkkkkkkk.',
  ],
};

/** Hund 12x8, blickt nach rechts. */
export const DOG_SPRITES: Record<'a' | 'b', readonly string[]> = {
  a: [
    '........kk..',
    'k..kkkkkkNk.',
    'nkknnnnnnknk',
    '.knnnnnnnnkk',
    '.knNNNNnnnk.',
    '.knk....knk.',
    '.kk.....kk..',
    '............',
  ],
  b: [
    '........kk..',
    '.k.kkkkkkNk.',
    'nkknnnnnnknk',
    '.knnnnnnnnkk',
    '.knNNNNnnnk.',
    '..knk..knk..',
    '..kk...kk...',
    '............',
  ],
};

/** Polizist 10x14, ein Bild für alle Richtungen. */
export const POLICE_SPRITES: Record<'a' | 'b', readonly string[]> = {
  a: [
    '..kkkkkk..',
    '.kBBBBBBk.',
    '.kBBccBBk.',
    '.kkkkkkkk.',
    '..kssssk..',
    '..kksskk..',
    '..kssssk..',
    '.kbbbbbbk.',
    'kbbbbbbbbk',
    'ksbbybbbsk',
    'kkbBBBBbkk',
    '.kBBBBBBk.',
    '.kBBkkBBk.',
    '.kkk..kkk.',
  ],
  b: [
    '..kkkkkk..',
    '.kBBBBBBk.',
    '.kBBccBBk.',
    '.kkkkkkkk.',
    '..kssssk..',
    '..kksskk..',
    '..kssssk..',
    '.kbbbbbbk.',
    'kbbbbbbbbk',
    'ksbbybbbsk',
    'kkbBBBBbkk',
    '.kBBBBBBk.',
    '.kBBkBBBk.',
    '.kkk.kkkk.',
  ],
};
