import type { SpotType } from '@pfandraiders/core';

/** Pixelmuster, Zeichen siehe PALETTE in pixelart.ts. Kacheln und Objekte 16x16, Spots 12x12. */
export const TILE_SPRITES: Record<string, readonly string[]> = {
  floor_0: [
    'gggggggggggggggG',
    'gggggggggggggggG',
    'gggggggggggggggG',
    'ggghhggggggggggG',
    'gggggggggggggggG',
    'gggggggggggggggG',
    'gggggggggggggggG',
    'gggggggggggggggG',
    'gggggggggggggggG',
    'ggggggggggGGgggG',
    'gggggggggggggggG',
    'gggggggggggggggG',
    'gggggghggggggggG',
    'gggggggggggggggG',
    'gggggggggggggggG',
    'GGGGGGGGGGGGGGGG',
  ],
  floor_1: [
    'gggggggggggggggG',
    'gggggggggggggggG',
    'gggggggggggggggG',
    'gggggggggggggggG',
    'ggggggggggghgggG',
    'gggggggggggggggG',
    'gggggggggggggggG',
    'gggggggggggggggG',
    'gggggGGggggggggG',
    'ggggggGggggggggG',
    'gggggggggggggggG',
    'gggggggggggggggG',
    'gghhgggggggggggG',
    'gggggggggggggggG',
    'gggggggggggggggG',
    'GGGGGGGGGGGGGGGG',
  ],
  floor_2: [
    'gggggggggggggggG',
    'gggggggggggggggG',
    'ggggggggGggggggG',
    'gggggggggggggggG',
    'gggggggggggggggG',
    'gggggggggggggggG',
    'ggghgggggggggggG',
    'gggggggggggggggG',
    'gggggggggggggggG',
    'gggggggggggggggG',
    'gggggggggggggggG',
    'gggggggggggghggG',
    'gggggggggggghggG',
    'ggGggggggggggggG',
    'gggggggggggggggG',
    'GGGGGGGGGGGGGGGG',
  ],
  wall_top_0: [
    'tttttttttttttttR',
    'trrrrrrrrrrrrrrR',
    'trrttrrrrrrrrrrR',
    'trrrrrrrrrrrrrrR',
    'tRRRRRRRRRRRRRRR',
    'trrrrrrrrrrrrrrR',
    'trrrrrrrrrtrrrrR',
    'trrrrrrrrrrrrrrR',
    'tRRRRRRRRRRRRRRR',
    'trrrrrrrrrrrrrrR',
    'trrrrrrttrrrrrrR',
    'trrrrrrrrrrrrrrR',
    'tRRRRRRRRRRRRRRR',
    'trrrrrrrrrrrtrrR',
    'trrrrrrrrrrrrrrR',
    'tRRRRRRRRRRRRRRR',
  ],
  wall_top_1: [
    'tttttttttttttttR',
    'trrrrrrrrttrrrrR',
    'trrrrrrrrrrrrrrR',
    'trrrrrrrrrrrrrrR',
    'tRRRRRRRRRRRRRRR',
    'trrrrrrrrrrrrrrR',
    'trrrtrrrrrrrrrrR',
    'trrrrrrrrrrrrrrR',
    'tRRRRRRRRRRRRRRR',
    'trrrrrrrrrrttrrR',
    'trrrrrrrrrrrrrrR',
    'trrrrrrrrrrrrrrR',
    'tRRRRRRRRRRRRRRR',
    'trrtrrrrrrrrrrrR',
    'trrrrrrrrrrrrrrR',
    'tRRRRRRRRRRRRRRR',
  ],
  wall_top_2: [
    'tttttttttttttttR',
    'trrrrrrrrrrrrrrR',
    'trrttrrrrrrrrrrR',
    'trrrrrrrrrrrrrrR',
    'tRRRRRRRRRRRRRRR',
    'trrrrrrrrkkkkrrR',
    'trrrrrrrrkttkrrR',
    'trrrrrrrrkkkkrrR',
    'tRRRRRRRRRRRRRRR',
    'trrrrrrrrrrrrrrR',
    'trrrrtrrrrrrrrrR',
    'trrrrrrrrrrrrrrR',
    'tRRRRRRRRRRRRRRR',
    'trrrrrrrrrrrrrrR',
    'trrrrrrrrrrrrrrR',
    'tRRRRRRRRRRRRRRR',
  ],
  wall_front: [
    'nnnnnnnnnnnnnnnn',
    'ffffffffffffffff',
    'ffffffffffffffff',
    'FfffffffFfffffff',
    'ffkkkkkfffffffff',
    'ffkwddkffkkkkkff',
    'ffkbbbkffknnnkff',
    'ffkbbbkffkNNNkff',
    'ffkBBBkffkNNNkff',
    'ffkBBBkffkNNNkff',
    'ffkkkkkffkNNykff',
    'FfffffffFkNNNkff',
    'ffffffffFkNNNkff',
    'fffffffffkNNNkff',
    'FFFFFFFFFFFFFFFF',
    'NNNNNNNNNNNNNNNN',
  ],
};

export const SPOT_SPRITES: Record<SpotType, { full: readonly string[]; empty: readonly string[] }> = {
  bus_stop: {
    full: [
      '............',
      'kBBBBBBBBBBk',
      'kbbbbbbbbbbk',
      'kkkkkkkkkkkk',
      '.kddddddddk.',
      '.k..yyo...k.',
      '.k.eoyy.y.k.',
      '.k.e...wy.k.',
      '.kkkkkkwkkk.',
      '.knnnnnnnnk.',
      '.kkkkkkkkkk.',
      '............',
    ],
    empty: [
      '............',
      'kBBBBBBBBBBk',
      'kbbbbbbbbbbk',
      'kkkkkkkkkkkk',
      '.kddddddddk.',
      '.k..yyo...k.',
      '.k..oyy...k.',
      '.k........k.',
      '.kkkkkkkkkk.',
      '.knnnnnnnnk.',
      '.kkkkkkkkkk.',
      '............',
    ],
  },
  bench: {
    full: [
      '............',
      '............',
      'kkkkkkkkkkkk',
      'knnnenwnynnk',
      'knnnenwnynnk',
      'kNNNNNNNNNNk',
      'kkkkkkkkkkkk',
      '.NkkkkkkkNk.',
      '.NknnnnnnNk.',
      '.NkkkkkkkNk.',
      '.kk......kk.',
      '............',
    ],
    empty: [
      '............',
      '............',
      'kkkkkkkkkkkk',
      'knnnnnnnnnnk',
      'knnnnnnnnnnk',
      'kNNNNNNNNNNk',
      'kkkkkkkkkkkk',
      '.NkkkkkkkNk.',
      '.NknnnnnnNk.',
      '.NkkkkkkkNk.',
      '.kk......kk.',
      '............',
    ],
  },
  bush: {
    full: [
      '....kkkk....',
      '..kkeeeekk..',
      '.keeEEeeeek.',
      'keeeeeeEeeek',
      'keeeyeeeEeek',
      'keEeyeeedeek',
      'keeEeewedeek',
      'keeeeeweEeek',
      'keeeeeeEeeek',
      '.keeeEEeeek.',
      '..kkeeeekk..',
      '....kkkk....',
    ],
    empty: [
      '....kkkk....',
      '..kkeeeekk..',
      '.keeEEeeeek.',
      'keeeeeeEeeek',
      'keeeeeeeEeek',
      'keEeeeeeeeek',
      'keeEeeeeeeek',
      'keeeeeeeEeek',
      'keeeeeeEeeek',
      '.keeeEEeeek.',
      '..kkeeeekk..',
      '....kkkk....',
    ],
  },
  bin: {
    full: [
      '...e..w.y...',
      '.kdeddwdydk.',
      '.kkekkkkkkk.',
      '..khggggGk..',
      '..khggggGk..',
      '..khgGGgGk..',
      '..khgGGgGk..',
      '..khgGGgGk..',
      '..khggggGk..',
      '..khggggGk..',
      '..kkkkkkkk..',
      '............',
    ],
    empty: [
      '............',
      '.kddddddddk.',
      '.kkkkkkkkkk.',
      '..khggggGk..',
      '..khggggGk..',
      '..khgGGgGk..',
      '..khgGGgGk..',
      '..khgGGgGk..',
      '..khggggGk..',
      '..khggggGk..',
      '..kkkkkkkk..',
      '............',
    ],
  },
  park: {
    full: [
      '.kEEEEEEEEk.',
      'kEEeEeeeeEEk',
      'kEEeeeeEeEEk',
      'kEEeeEeeeEEk',
      '.kEEEEEEEEk.',
      '..kkknNkkk..',
      'kkkkknNkkkkk',
      'EEEEEnNEEEEE',
      'eeeeenNeeeEe',
      'eeweenNeyede',
      'eewyeeeeyEde',
      'eeeyeeeeeeee',
    ],
    empty: [
      '.kEEEEEEEEk.',
      'kEEeEeeeeEEk',
      'kEEeeeeEeEEk',
      'kEEeeEeeeEEk',
      '.kEEEEEEEEk.',
      '..kkknNkkk..',
      'kkkkknNkkkkk',
      'EEEEEnNEEEEE',
      'eeeeenNeeeEe',
      'eeEeenNeeeee',
      'eeeeeeeeeEee',
      'eeeeeeeeeeee',
    ],
  },
};

export const OBJECT_SPRITES: { dropoff: readonly string[]; shop: readonly string[] } = {
  dropoff: [
    '..kkkkkkkkkkkk..',
    '..kddddddddddk..',
    '..kbkkkkkkkkBk..',
    '..kbkeEeEeekBk..',
    '..kbkeeeeeekBk..',
    '..kbkkkkkkkkBk..',
    '..kbbbbbbbbbBk..',
    '..kbkkkkkkkkBk..',
    '..kbknnnnnnkBk..',
    '..kbkNNNNNykBk..',
    '..kbkNNNNNNkBk..',
    '..kbkkkkkkkkBk..',
    '..kbbccbbyybBk..',
    '..kbbbbbbbbbBk..',
    '..kBBBBBBBBBBk..',
    '..kkkkkkkkkkkk..',
  ],
  shop: [
    'kkkkkkkkkkkkkkkk',
    'kyyooyyooyyooyyk',
    'kyyooyyooyyooyyk',
    'kyyooyyooyyooyyk',
    'kooooooooooooook',
    '.kffffffffffffk.',
    '.kfkkkkkkkkkkfk.',
    '.kfkbbbbbbbbkfk.',
    '.kfkckkekkykkfk.',
    '.kkkkkkkkkkkkkk.',
    '.knnnnnnnnnnnnk.',
    '.knnnnnnnnnnnnk.',
    '.kNNNNNNNNNNNNk.',
    '.kffffffffffffk.',
    'kFFFFFFFFFFFFFFk',
    'kkkkkkkkkkkkkkkk',
  ],
};
